#+TITLE:Pokemon Japanese School Translation
#+AUTHOR:Archenoth
#+EMAIL:Archenoth@gmail.com
:SETTINGS:
#+STARTUP: hidestars
#+DRAWERS: KANA SETTINGS
#+LINK: translate https://translate.google.com/?sl=ja&tl=en&hl=en&q=
#+LINK: jisho http://jisho.org/search?utf8=%E2%9C%93&keyword=
#+TAGS: Translation(t)
#+OPTIONS: ^:nil H:3 p:nil todo:nil toc:nil
#+PROPERTY: header-args :exports both :eval never-export
#+LANGUAGE: jp
#+LATEX_CLASS: japanese
#+LATEX_HEADER: \usepackage{textcomp}
#+LATEX_HEADER: \usepackage{parskip}
#+LATEX_HEADER: \usemintedstyle{friendly}
#+LATEX_HEADER: \renewcommand{\contentsname}{Table of Contents}
#+LATEX: \pagebreak
:END:

This file will be my translation of Pokemon Green, and will accompany the =.sav= file included in this repository.

Note, that this isn't my attempt at localizing Pokemon Green, so some of the English may sound kinda weird. That's because I will attempt to write the English in such a way as to understand the Japanese as literally as possible.

Also, you may need some Japanese knowledge to follow along, though I will link to most of the grammar points that are beyond a basic level. I will also link a ridiculous amount of vocabulary so they are easy to look up. Even so, it is recommended to be familiar with [[https://www.tofugu.com/japanese/learn-hiragana/][Hiragana]] and [[https://www.tofugu.com/japanese/learn-katakana/][Katakana]], as well as some basic Japanese Grammar. I'll try to explain some of the more tricky points though.

* The title and menus
There really are only a few things to translate here, and those are the title:

#+BEGIN_EXAMPLE
ポケットモンスター
#+END_EXAMPLE

This says "Pocket Monsters" ([[jisho:ポッケトモンスター][ポッケトモンスター]]), or what "Pokemon" ([[jisho:ポケモ
ン][ポケモン]]) is a contraction of.

The following menu has two options:

#+BEGIN_EXAMPLE
さいしょからはじめる
#+END_EXAMPLE
This means 「Start ([[jisho:はじめる][はじめる]]) from ([[jisho:から][から]]) the beginning ([[jisho:さいしょ][さいしょ]])」

#+BEGIN_EXAMPLE
せっていを かえる
#+END_EXAMPLE
This means 「Change ([[jisho:かえる][かえる]]) settings ([[jisho:せってい][せってい]])」

After saving, a third option appears at the top:
#+BEGIN_EXAMPLE
つづきからはじめる
#+END_EXAMPLE
「Start ([[jisho:はじめる][はじめる]]) from ([[jisho:から][から]]) last ([[jisho:つづき][つづき]])」

** Settings
#+BEGIN_EXAMPLE
はなしの はやさ
  はやい   ふつう   おそい
#+END_EXAMPLE
This top setting is talking ([[jisho:はなし][はなし]]) speed ([[jisho:はやさ][はやさ]]), and the three choices are fast ([[jisho:はやい][はやい]]) normal ([[jisho:ふつう][ふつう]]), and slow ([[jisho:おそい][おそい]])。

#+BEGIN_EXAMPLE
せんとう アニメーション
  じっくり みる   とばして みる
#+END_EXAMPLE

This setting means「Battle ([[jisho:せんとう][せんとう]]) animations ([[jisho:アニメーション][アニメーション]])」, and the two options are 「Thoroughly ([[jisho:じっくり][じっくり]]) see ([[jisho:みる][みる]])」and 「Omit ([[jisho:とばして][とばして]]) seeing ([[jisho:みる][みる]]) them」。

So basically, "See battle animations" or "Omit battle animations".

#+BEGIN_EXAMPLE
しあいの ルール
  いれかえタイプ   からぬきタイプ
#+END_EXAMPLE
This setting means「Match ([[jisho:しあい][しあい]]) rules ([[jisho:ルール][ルール]])」and the two options are「Switching ([[jisho:いれかえ][いれかえ]]) type ([[jisho:タイプ][タイプ]])」and「From ([[jisho:から][から]]) succession ([[jisho:ぬ き][ぬき]]) type ([[jisho:タイプ][タイプ]])」

These are the two classic battle types for Pokemon, the switch type which lets you switch Pokemon after you defeat an opponent (Easy mode) and "Set type" where you have to use a turn to switch. (Which is the best type, and you should use it.)

Finally, the last word in the screen means "Finish" ([[jisho:おわり][おわり]]) .

Now, time for the actual game!

* The Oakster's speech
The game begins with a speech from, as we know him, Professor Oak:
#+BEGIN_EXAMPLE
はじめまして！

ポケット モンスターの せかいへ
ようこそ！
#+END_EXAMPLE

This says "Hello! ([[jisho:はじめまして][はじめまして]]！) Welcome ([[jisho:ようこそ][ようこそ]]) to ([[https://www.renshuu.org/grammar/468/%E3%81%B8][へ]]) the world ([[jisho:せかい][せかい]]) of ([[https://www.renshuu.org/grammar/132/の][の]]) Pocket Monsters ([[jisho:ポケット モンスター][ポケット モンスター]])！"

#+BEGIN_EXAMPLE
わたしの なまえは オーキド
みんなからは ポケモン はかせと
したわれた おるよ
#+END_EXAMPLE
My ([[jisho:わたし][わたし]] [[jisho:の][の]]) name ([[jisho:なまえ][なまえ]]) is ([[jisho:は][は]]) Okkido. ([[jisho:オーキド][オーキド]]) To ([[jisho:から][から]] [[jisho:は][は]]) everyone ([[jisho:みんな][みんな]]) I have been ([[jisho:した][したわれて]] [[jisho:おる][おる]]) known as ([[jisho:と][と]]) the Pokemon ([[jisho:ポケモン][ポケモン]]) Dr. ([[jisho:はかせ][はかせ]]) !([[jisho:よ][よ]])

Okkido! That is his original name in Japanese.

The と here is like a quote, and したわれて is the [[https://www.renshuu.org/grammar/51/Passive][passive]] [[https://www.renshuu.org/grammar/479/Past%20Casual][past-tense]] [[https://www.renshuu.org/grammar/101/%E3%81%A6][て-form]] of [[jisho:した][した]].

So it's like saying "times that everyone has called me the Pokemon Dr. have existed", or "Everyone calls me the Pokemon Professor".

#+BEGIN_EXAMPLE
この せかいには
ポケット モンスターと よばれる
いきもの たちが
いたるところに すんでいる！
#+END_EXAMPLE

For ([[jisho:には][には]]) this ([[jisho:この][この]]) world ([[jisho:せかい][せかい]]), the living things ([[jisho:いきもの][いきもの]]) called ([[jisho:よばれる][よばれる]]) Pocket Monsters ([[jisho:ポケット モンスター][ポケット モンスター]]) live ([[jisho:すんでいる][すんでいる]]) everywhere ([[jisho:いたるところ][いたるところ]]).

"called Pocket Monsters" (ポケット モンスター と よばれる) [[http://www.guidetojapanese.org/subclause.html#part3][modifies]] 「いきもの」(Living thing) たち (plural), giving us "The living things called Pocket Monsters..."

The と, once again is a quote. So 「ポケット モンスター と よばれる」 is essentially 「called "ポケット モンスター"」.

すんでいる is the [[https://www.renshuu.org/grammar/16/%E3%81%A6%E3%81%84%E3%82%8B][progressive]] form of [[jisho:すむ][すむ]], which basically is like putting an "-ing" at the end of a verb. (Live vs Living)

This makes the entire sentence more-less "In this world, the creatures known as Pokemon live everywhere!"

#+BEGIN_EXAMPLE
その ポケモン という いきものを
ひとは ペットに したり
しょうぶに つかったり。。。
#+END_EXAMPLE
Those ([[jisho:その][その]]) living things ([[jisho:いきもの][いきもの]]) known as ([[jisho:という][という]]) Pokemon ([[jisho:ポケモン][ポケモン]]): some people ([[jisho:ひと][ひと]] ... [[jisho:したり][したり]]) have them as ([[jisho:に][に]] [[jisho:した][した]]) pets ([[jisho:ペット][ペット]]) and some use them ([[jisho:つかったり][つかったり]]) for ([[jisho:に][に]]) matches ([[jisho:しょうぶ][しょうぶ]]).

This uses [[http://www.punipunijapan.com/japanese-grammar-tari-tari/][たり-form]] to list out a number of candidate activities. In this case, having Pokemon as pets and using Pokemon for matches.

The sentence overall reads like "Some people keep these creatures known as Pokemon as pets, and others use them for battles."

#+BEGIN_EXAMPLE
そして。。。
#+END_EXAMPLE
"[[http://thejapanesepage.com/grammar/chapter_one/and_to_soshite][and]]..."

#+BEGIN_EXAMPLE
わたしは この ポケモンの
けんきゅうを してる というわけだ
#+END_EXAMPLE
The research ([[jisho:けんきゅう][けんきゅう]]) of these ([[jisho:この][この]] ... [[jisho:の][の]]) Pokemon ([[jisho:ポケモン][ポケモン]]) is my ([[jisho:わたし][わたし]] [[jisho:は][は]]) reason ([[https://www.renshuu.org/grammar/489/%E3%82%8F%E3%81%91%E3%81%A0][という わけ だ]]).

#+BEGIN_EXAMPLE
では はじめに きもの なまえを
おしえて もらおう！
#+END_EXAMPLE
So ([[jisho:では][では]]) to start ([[jisho:はじめに][はじめに]]) give me ([[jisho:もらおう][もらおう]]) teaching ([[jisho:おしえて][おしえて]]) of your ([[jisho:きみ][きみ]] [[jisho:の][の]]) name ([[jisho:なまえ][なまえ]])!

In Japanese, when requesting something, you sometimes ask people to give you actions, and you sometimes give out actions to other people. In this case, Okkido is asking you to give him the action of you teaching him your name.

The おしえて is the て-form of [[jisho:おしえる][おしえる]], so it is kinda like an order in a way.

The names we can choose from are:
#+BEGIN_EXAMPLE
じぶんできめる
グリーン
シゲル
ジョン
#+END_EXAMPLE

Those are Green ([[jisho:グリーン][グリーン]]), Shigeru ([[jisho:シゲル][シゲル]]), Jon ([[jisho:ジョン][ジョン]]), and Decide ([[jisho:きめる][きめる]]) by ([[jisho:で][で]]) myself ([[jisho:じぶん][じぶん]]).

Of course, with so much name confusion, who wouldn't want to play as Green?

#+BEGIN_EXAMPLE
ふむ。。。
クリーン と いうんだな！
#+END_EXAMPLE
Hmm... ([[jisho:ふむ][ふむ]])
"Green" ([[jisho:グリーン][グリーン]] [[jisho:と][と]]) is what you are named ([[jisho:いう][いう]] [[jisho:んだ][んだ]]) huh? ([[jisho:な][な]])

Once again, the と here is a quote. The (いうんだ) is adding information to the current context ([[http://japanese.stackexchange.com/a/5399/10600][んだ]]) using what you called yourself. (グリーン と いう)

Also, the "ふむ" here is actually an onomatopoeia for "Hmm", and not read like "fu-mu" or anything.

#+BEGIN_EXAMPLE
こいつは わたしの まご
きみの おさななじみであり
ライバル である
#+END_EXAMPLE
This guy ([[jisho:こいつ][こいつ]]) is ([[jisho:は][は]]) my ([[jisho:わたし][わたし]] [[jisho:の][の]]) grandchild ([[jisho:まご][まご]]) He exists ([[jisho:あり][あり]]) as ([[jisho:で][で]]) your ([[jisho:きみ][きみ]] [[jisho:の][の]]) childhood friend ([[jisho:おさななじみ][おさななじみ]]) He exists ([[jisho:ある][ある]]) as ([[jisho:で][で]]) a rival ([[jisho:ライバル][ライバル]])

Lots of "exists" here. The difference between ある and あり is that あり is stem-form, which allows you to chain other statements after it, so basically this can be parsed as two sentences, with the second containing two statements separated by "and":

#+BEGIN_EXAMPLE
  This guy is my grandchild.
  He is your childhood friend
  and rival
#+END_EXAMPLE

#+BEGIN_EXAMPLE
。。。えーと？
なまえは なんて いったかな？
#+END_EXAMPLE
...uhh? ([[jisho:えーと][えーと]])
What ([[jisho:なんて][なんて]]) was ([[jisho:いった][いった]]) the name ([[jisho:なまえ][なまえ]])?([[jisho:か][か]] [[jisho:な][な]]？)

Classic Professor dementia.

The name here is of course, from context of the previous sentences. He is asking about the name of his grandson. なんて is like saying "what" with a small touch of "Oh dear" in it. いった is the past-tense of "to name" , which is why I put it next to "was".

The names are:
#+BEGIN_EXAMPLE
じぶんできめる
レード
サトシ
ジャック
#+END_EXAMPLE
So once again we have "Decide ([[jisho:きめる][きめる]]) by ([[jisho:で][で]]) myself ([[jisho:じぶん][じぶん]])" and three other names: Red ([[jisho:レード][レード]]), Satoshi ([[jisho:サトシ][サトシ]]), and Jack ([[jisho:ジャック][ジャック]]).

The rival from the original games was definitely Red. (Smell ya later!)

#+BEGIN_EXAMPLE
そうだ そうだ！ おもいだしたぞ
レッド という なまえだ
#+END_EXAMPLE
Right ([[jisho:そうだ][そうだ]]) right ([[jisho:そうだ][そうだ]])! I remembered ([[jisho:おもいだした][おもいだした]])!
The name ([[jisho:なまえ][なまえ]]) is known as ([[jisho:という][という]]) Red ([[jisho:レード][レード]])

The ぞ is a masculine sentence end that makes an assertion, and おもいだした is the past-tense form of [[jisho:おもいだす][おもいだす]].

The crazy sentence reordering here is because という is a way of saying something is known as something else. For example "ポケモン という ケーム" which is "Pokemon という game", or "The game known as Pokemon".

#+BEGIN_EXAMPLE
グリーン！
#+END_EXAMPLE
"Green!"

#+BEGIN_EXAMPLE
いよいよ これから
きみの ものがたりの はじまりだ！
#+END_EXAMPLE
Finally ([[jisho:いよいよ][いよいよ]]) from now on ([[jisho:これから][これから]]) this is ([[jisho:だ][だ]]) your ([[jisho:きみ][きみ]] [[jisho:の][の]]) tale ([[jisho:ものがたり][ものがたり]]) beginning ([[jisho:はじまりだ][はじまり]])!

#+BEGIN_EXAMPLE
ゆめと ぼうけんと！
ポケット モンスターの せかいへ！
#+END_EXAMPLE
Dreams ([[jisho:ゆめ][ゆめ]]) and adventures ([[jisho:ぼうけん][ぼうけん]])!
Go to ([[jisho:へ][へ]]) the World ([[jisho:せかい][せかい]]) of ([[jisho:の][の]]) Pocket Monsters ([[jisho:ポケット モンスター][ポケット モンスター]])!

The [[https://www.renshuu.org/grammar/110/%E3%81%A8][と]] here is an exhaustive list. This means that you can't add things to it like with [[https://www.renshuu.org/grammar/469/%E3%82%84][や]]. The [[https://www.renshuu.org/grammar/468/%E3%81%B8][へ]] at the end means "Go to" basically.

#+BEGIN_EXAMPLE
レード ゴー！
#+END_EXAMPLE
"Red go!"

* The in-game menu
The in-game menu has a few entries
#+BEGIN_EXAMPLE
ポケモン
どうぐ
グリーン
レポート
せってい
とじる
#+END_EXAMPLE

And they mean:
 - Pokemon ([[jisho:ポケモン][ポケモン]])
 - Tool ([[jisho:どうぐ][どうぐ]])
 - Green ([[jisho:グリーン][グリーン]])
 - Report ([[jisho:レポート][レポート]])
 - Settings ([[jisho:せってい][せってい]])
 - Close ([[jisho:とじる][とじる]])

The only non-obvious one in here is "Report", which basically means save.

** Save
The save screen shows text in about two trillion different windows:

Details:
#+BEGIN_EXAMPLE
しゅじんんこう   グリーン
もってるバッジ ０ こ
ポケモンずかん ０ひき
プレイじかん  ０：２２
#+END_EXAMPLE
Which would be:

 - Protagonist ([[jisho:しゅじんんこう][しゅじんんこう]])   Green ([[jisho:グリーン][グリーン]])
 - Held ([[jisho:もってる][もってる]]) Badges ([[jisho:バッジ][バッジ]]) ０ Articles ([[jisho:こ][こ]])
 - Pokemon ([[jisho:ポケモン][ポケモン]]) Field guide ([[jisho:ずかん][ずかん]]) ０ Creatures ([[jisho:ひき][ひき]])
 - Play ([[jisho:プレイ][プレイ]]) time ([[jisho:じかん][じかん]])  ０：２２

(Yes I did spend 22 minutes saving)

Question:
#+BEGIN_EXAMPLE
ここまでの かつやくを
ポケモンレポートに かきこみますか？
#+END_EXAMPLE
Will you save ([[jisho:かきこみます][かきこみます]] [[jisho:か][か]]) in ([[jisho:に][に]]) the Pokemon Report,
([[jisho:ポケモンレポート][ポケモンレポート]]) activities ([[jisho:かつやく][かつやく]]) up until now ([[jisho:ここまで][ここまで]])?

Response:
#+BEGIN_EXAMPLE
はい
いいえ
#+END_EXAMPLE
Yes ([[jisho:はい][はい]]) and no ([[jisho:いいえ][いいえ]])

* Your house!
You find yourself in your room at the beginning of the game playing video games. Woah, meta already.

If you interact with it, you see the following:
#+BEGIN_EXAMPLE
グリーンは
ファミコンを してる！
#+END_EXAMPLE
Green ([[jisho:グリーン][グリーン]]) is ([[jisho:は][は]]) playing ([[jisho:を][を]] [[jisho:してる][してる]]) the Famicon! ([[jisho:ファミコン][ファミコン]])

#+BEGIN_EXAMPLE
…… …… よし！
#+END_EXAMPLE
...... ...... alright! ([[jisho:よし][よし]])

#+BEGIN_EXAMPLE
そろそろ でかけよう！
#+END_EXAMPLE
Lets go ([[jisho:でかけよう][でかけよう]]) soon! ([[jisho:そろそろ][そろそろ]])

The でかけよう is でかける in what's called "[[http://www.guidetojapanese.org/desire.html#part4][Volitional form]]", which is a way to specify desire to do something. So the player is basically saying "Alright! Lets go!".

When you walk downstairs there is a room with a TV which, when interacted with shows:

#+BEGIN_EXAMPLE
みえない……
#+END_EXAMPLE
Can't see. ([[jisho:みえない][みえない]])

...oh, ha! That's because I looked at the side of the TV. Trying to watch it like a normal to-be Pokemon trainer shows:

#+BEGIN_EXAMPLE
テレビで えいがを やってる！
おとこのこが ４にん
せんろのうえを ありてる……
#+END_EXAMPLE
On the ([[jisho:で][で]]) TV ([[jisho:テレビ][テレビ]]) a movie ([[jisho:えいが][えいが]]) is ([[jisho:を][を]]) playing! ([[jisho:やってる][やってる]])
Four boys ([[jisho:おとこのこ][おとこのこ]] [[jisho:が][が]] ４[[jisho:にん][にん]]) are ([[jisho:を][を]] [[jisho:ありてる][ありてる]]) on top ([[jisho:の][の]] [[jisho:うえ][うえ]]) of
train tracks ([[jisho:せんろ][せんろ]])......

#+BEGIN_EXAMPLE
…… ぼくも もう いかなきゃ！
#+END_EXAMPLE
I ([[jisho:ぼく][ぼく]]) also ([[jisho:も][も]]) have to go! ([[jisho:いかなきゃ][いかなきゃ]])

The いかなきゃ here is basically a way of saying "Gotta go!". Adding [[http://www.guidetojapanese.org/completeguide.html#part4.haveto.html][きゃ]] to the stem of negative form verb is basically saying you must do that thing.

Also in the room there is a bookshelf that when interacted with shows:

#+BEGIN_EXAMPLE
ポケモンの ほんが いっぱい！
#+END_EXAMPLE
It is full ([[jisho:いっぱい][いっぱい]]) of ([[jisho:が][が]]) Pokemon books! ([[jisho:ポケモン][ポケモン]] [[jisho:の][の]] [[jisho:ほん][ほん]])

And finally, of course, is your mother, who says:
#+BEGIN_EXAMPLE
おかあさん『…… そうね
おとこのこは いっか
たびに でるもの なのよ
うん…… テレビの はなしよ！
#+END_EXAMPLE
Mother: ([[jisho:おかあさん][おかあさん]]) ...... Ah ([[jisho:そうね][そうね]])
Boys ([[jisho:おとこのこ][おとこのこ]]) leave ([[jisho:でる][でる]]) for ([[jisho:に][に]]) trips ([[jisho:たび][たび]]) from home ([[jisho:いっか][いっか]])
huh? ([[jisho:なの][なの]]) Yeah ([[jisho:うん][うん]])...... The TV ([[jisho:テレビ][テレビ]]) talked about it ([[jisho:の][の]] [[jisho:はなし][はなし]])!

Also, this bothers me, why is there no closing 』? Will this be the standard way to quote characters? Maybe something in the next part?

#+BEGIN_EXAMPLE
そういえば
となりの オーキドはかせが
あなたを よんでたわよ
#+END_EXAMPLE
Which reminds me ([[jisho:そういえば][そういえば]])
The neighbor ([[jisho:となり][となり]]) Dr. Okkido ([[jisho:の][の]] [[jisho:オーキド][オーキド]] [[jisho:はかせ][はかせ]])
has invited ([[jisho:よんでた][よんでた]]) you ([[jisho:あなた][あなた]])!([[jisho:わよ][わよ]])

Nope, no closing 』.

Also, because it collides with [[jisho:よむ][よむ]], I should note that よんでた is the past-て form [[jisho:よぶ][よぶ]].

And with that, we can get moving into the rest of the town!

* The town
Ah! Pallet Town. Not a very big place, and you start out at the door of your house. There is a sign there that reads:
#+BEGIN_EXAMPLE
ここは グリーン のいえ
#+END_EXAMPLE
Here ([[jisho:ここ][ここ]]) is ([[jisho:は][は]]) Green([[jisho:グリーン][グリーン]])'s([[jisho:の][の]]) house ([[jisho:いえ][いえ]])

There is also a sign just south of your house that reads:
#+BEGIN_EXAMPLE
ここは マサラ タウン
マサラは まっしろ はじまりのいろ
#+END_EXAMPLE
Here ([[jisho:ここ][ここ]]) is ([[jisho:は][は]]) Masara ([[jisho:マサラ][マサラ]]) Town ([[jisho:タウン][タウン]])
Masara ([[jisho:マサラ][マサラ]]) is ([[jisho:は][は]]) the color ([[jisho:いろ][いろ]]) of ([[jisho:の][の]]) a pure white ([[jisho:まっしろ][まっしろ]]) beginning ([[jisho:はじまり][はじまり]])

A pure white beginning? The entire game is black and white! (Wait, does that mean I am I translating Pokemon Black and White in a way?)

Anywho...

There is also a girl NPC who wanders around the west part of town. When you talk to her, she says:
#+BEGIN_EXAMPLE
わたしも
ポケモンを そだててるの！
つよく なれば
ガードマンの かわりに なるしね
#+END_EXAMPLE
I ([[jisho:わたし][わたし]]) also ([[jisho:も][も]])
am raising ([[jisho:を][を]] [[jisho:そだててる][そだててる]]) Pokemon! ([[jisho:ポケモン][ポケモン]])
If I become ([[jisho:なれば][なれば]]) strong ([[jisho:つよく][つよく]])
I can become ([[jisho:なるし][なるし]]) a guardman ([[jisho:ガードマン][ガードマン]]) substitute ([[jisho:かわり][かわり]])

A guardman? Woah. Anyway, there are two tricky things in this sentence, one is that the ば in なれば is a conditional [[jisho:なる][なる]]. Changing the last sound to an え and adding ば is you do [[http://www.learn-japanese-adventure.com/japanese-conditional-form-ba-nara.html][conditional verbs]]. The second is the mysterious し near the end, which basically [[http://selftaughtjapanese.com/2014/05/04/japanese-phrase-ender-%E3%81%97-shi/][gives reason]] to the second sentence with the first sentence.

...oh, and I guess I should mention that the そだててる is the version of [[jisho:そだてる][そだてる]] that means it is currently happening.

After talking to the guardman-to-be, we can talk to the dude walking around the southeast part of town, he says:
#+BEGIN_EXAMPLE
かがくの ちからって すげー！
いまは パソコンつうしんで
どうぐや ポケモンを
データにして おくれるんだと
#+END_EXAMPLE
The power ([[jisho:ちから][ちから]]) of ([[jisho:の][の]]) science ([[jisho:かがく][かがく]]) is incredible! ([[jisho:すげー][すげー]])
The case is, ([[jisho:んだ][んだ]]) now ([[jisho:いま][いま]]) with ([[jisho:で][で]]) computer ([[jisho:パソコン][パソコン]]) communications ([[jisho:つうしん][つうしん]]), tools ([[jisho:どうぐ][どうぐ]]) and ([[jisho:や][や]]) Pokemon ([[jisho:ポケモン][ポケモン]]) can be sent ([[jisho:おくれる][おくれる]]).

The first bit is emphasized by the certainty of [[jisho:って][って]] at the end of the word [[jisho:ちから][ちから]]. And the おくれる is the potential form of [[jisho:おくる][おくる]]. (Which is where "can" comes from.)

The と at the end adds a bit of [[http://www.guidetojapanese.org/forum/viewtopic.php?id=7317#p63118][emphasis and emotion]] to the sentence.

And finally, the sign in front of the large building to the north of techno-dude says:
#+BEGIN_EXAMPLE
ここは オーキド はかせの
ポケモン けんんきゅうじょ
#+END_EXAMPLE
Here ([[jisho:ここ][ここ]]) is ([[jisho:は][は]]) Dr. Okkido([[jisho:オーキド][オーキド]] [[jisho:はかせ][はかせ]])'s([[jisho:の][の]])
Pokemon ([[jisho:ポケモン][ポケモン]]) laboratory ([[jisho:けんんきゅうじょ][けんんきゅうじょ]])

Hm, this is where we should go... But there is still one more house, the one east of ours.

There is a sign there that says:
#+BEGIN_EXAMPLE
ここは レッド のいえ
#+END_EXAMPLE
Here ([[jisho:ここ][ここ]]) is ([[jisho:は][は]]) Red([[jisho:レッド][レッド]])'s([[jisho:の][の]]) house ([[jisho:いえ][いえ]])

Uh oh, the competition. Let's go in!

I'm sure Okkido can wait.

* Red's house
In Red's house, there is only one floor (Where do they sleep?) and Red's sister. When you talk to her she says:

#+BEGIN_EXAMPLE
こんにちは グリーンくん！
おとうとの レッドなら
おじいちゃんの けんきゅうじょよ
#+END_EXAMPLE
Hello ([[jisho:こんにちは][こんにちは]]) Green! ([[jisho:ぐりーん][ぐりーん]])
As for ([[jisho:なら][なら]]) my younger brother, ([[jisho:おとうと][おとうと]]) Red ([[jisho:レッド][レッド]]) /he is at/
my grandpa ([[jisho:おじいちゃん][おじいちゃん]])'s([[jisho:の][の]]) laboratory ([[jisho:けんきゅうじょ][けんきゅうじょ]]), hey? ([[jisho:よ][よ]])

[[jisho:なら][なら]] is kinda like an if statement, so more literally it is like saying "If it is Red, my grandpa's laboratory".

In front of her is a book that says:
#+BEGIN_EXAMPLE
カントー ちほうの ちずだ！
…… もらえたら うれしい？
#+END_EXAMPLE
A Kanto ([[jisho:カントー][カントー]]) Region ([[jisho:ちほう][ちほう]]) map! ([[jisho:ちず][ちず]])
......Would I be happy ([[jisho:うれしい][うれしい]]) if ([[jisho:たら][たら]]) I got ([[jisho:もらう][もらう]]) /one/?

There are also a number of bookcases in the room, which when interacted with say:
#+BEGIN_EXAMPLE
ほんだなに ならんでいるのは
ポケモンの ほん ばかりだ
#+END_EXAMPLE
Standing in a line ([[jisho:ならんでいる][ならんでいる]]) in ([[jisho:に][に]]) the bookshelf ([[jisho:ほんだな][ほんだな]]),
([[jisho:のは][のは]]) nothing ([[jisho:ばかり][ばかり]]) but Pokemon ([[jisho:ポケモン][ポケモン]]) books. ([[jisho:の][の]] [[jisho:ほん][ほん]])

The ならんでいる is a progressive [[jisho:ならぶ][ならぶ]].

There is also a map on the wall that shows the text:
#+BEGIN_EXAMPLE
タウンマップだ！
#+END_EXAMPLE
Town ([[jisho:タウン][タウン]]) Map! ([[jisho:マップ][マップ]])

...and that's it.

Alright, time to go to the lab!
